# Generated by Django 5.1.3 on 2024-11-17 15:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('event_list', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Titel'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'sub-title', 'label': 'Subtitel'}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Vortrag', 'Talk'), ('Hybride Vortrag', 'Hybrid'), ('Online Vortrag', 'Online'), ('Beobachtungsabend', 'Observe'), ('Ausflug', 'Excursion')], 'help_text': 'Liste von Veranstaltungen', 'label': 'Art der Veranstaltung'}), 5: ('wagtail.blocks.StructBlock', [[('event_type', 4)]], {})}, default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Titel'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'sub-title', 'label': 'Subtitel'}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SingleEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Vortrag', 'Talk'), ('Hybride Vortrag', 'Hybrid'), ('Online Vortrag', 'Online'), ('Beobachtungsabend', 'Observe'), ('Ausflug', 'Excursion')])),
                ('location', models.CharField(blank=True, default='Deutsches Museum', max_length=120)),
                ('referent', models.CharField(blank=True, max_length=120)),
                ('abstract', wagtail.fields.RichTextField(blank=True, max_length=800)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('cancelled', models.BooleanField(default=False)),
                ('booked_out', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
