# Generated by Django 5.1.3 on 2024-12-01 16:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('event_list', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Vortrag', 'Talk'), ('Hybride Vortrag', 'Hybrid'), ('Online Vortrag', 'Online'), ('Beobachtungsabend', 'Observe'), ('Ausflug', 'Excursion')], 'help_text': 'Liste von Veranstaltungen', 'label': 'Art der Veranstaltung'}), 6: ('wagtail.blocks.StructBlock', [[('event_type', 5)]], {})}, default=[]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, default=[]),
        ),
    ]
