# Generated by Django 5.0.3 on 2024-07-28 16:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('homepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.homepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.homepage',),
        ),
        migrations.CreateModel(
            name='SingleEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Vortrag', 'Talk'), ('Hybride Vortrag', 'Hybrid'), ('Online Vortrag', 'Online'), ('Beobachtungsabend', 'Observe'), ('Ausflug', 'Excursion')])),
                ('location', models.CharField(blank=True, default='Deutsches Museum', max_length=120)),
                ('referent', models.CharField(blank=True, max_length=120)),
                ('abstract', wagtail.fields.RichTextField(blank=True, max_length=800)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('cancelled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
