# Generated by Django 5.1.3 on 2025-02-07 16:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_singleevent_event_title_alter_singleevent_abstract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleevent",
            name="needs_reservation",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h1", 0),
                    ("h2", 1),
                    ("h3", 2),
                    ("paragraph", 3),
                    ("image", 4),
                    ("event_list", 6),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "h1", "label": "Kopfzeile 1"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "h2", "label": "Kopfzeile 2"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "h3", "label": "Kopfzeile 3"},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Vortrag", "Vortrag"),
                                ("Hybride Vortrag", "Hybride Vortrag"),
                                ("Online Vortrag", "Online Vortrag"),
                                ("Beobachtungsabend", "Beobachtungsabend"),
                                ("Ausflug", "Ausflug"),
                            ],
                            "help_text": "Liste von Veranstaltungen",
                            "label": "Art der Veranstaltung",
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("event_type", 5)]], {}),
                },
                default=[],
            ),
        ),
        migrations.AlterField(
            model_name="singleevent",
            name="abstract",
            field=wagtail.fields.RichTextField(default="", max_length=800),
        ),
        migrations.AlterField(
            model_name="singleevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Vortrag", "Vortrag"),
                    ("Hybride Vortrag", "Hybride Vortrag"),
                    ("Online Vortrag", "Online Vortrag"),
                    ("Beobachtungsabend", "Beobachtungsabend"),
                    ("Ausflug", "Ausflug"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="singleevent",
            name="referent",
            field=models.CharField(default="", max_length=120),
        ),
    ]
