# Generated by Django 5.0.3 on 2024-11-14 23:20

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_eventpage_singleevent'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='homepage_ptr',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', label='Titel')), ('subheading', wagtail.blocks.CharBlock(form_classname='sub-title', label='Subtitel')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('event_list', wagtail.blocks.StructBlock([('event_type', wagtail.blocks.ChoiceBlock(choices=[('Vortrag', 'Talk'), ('Hybride Vortrag', 'Hybrid'), ('Online Vortrag', 'Online'), ('Beobachtungsabend', 'Observe'), ('Ausflug', 'Excursion')], help_text='Liste von Veranstaltungen', label='Art der Veranstaltung'))]))], default=[]),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleevent',
            name='booked_out',
            field=models.BooleanField(default=False),
        ),
    ]
