# Generated by Django 5.1.6 on 2025-05-23 18:20

import django.db.models.deletion
from django.db import migrations, models


def set_image_to_null(apps, schema_editor):
    SingleEvent = apps.get_model("home", "SingleEvent")
    # Set all existing 'image' field values to None (NULL)
    # This ensures that when the field type changes to ForeignKey,
    # there are no invalid string values to convert to integers.
    SingleEvent.objects.all().update(image=None)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_galleryindexpage_gallerypage_photopage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        # Step 1: Temporarily allow NULL for the 'image' field
        # This is crucial if your original ImageField had null=False
        migrations.AlterField(
            model_name="singleevent",
            name="image",
            field=models.CharField(
                max_length=255, null=True, blank=True
            ),  # Assuming it was CharField for paths
        ),

        # Step 2: Run a Python function to clear the existing 'image' data
        # This will now succeed because the field allows NULL
        migrations.RunPython(set_image_to_null, migrations.RunPython.noop),
        
        # Step 3: Alter the field type to ForeignKey (this will now work as the column is clean and allows NULL)
        migrations.AlterField(
            model_name="singleevent",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        )
    ]
