# Generated by Django 5.1.6 on 2025-04-04 20:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallerypage_photopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='photopage',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photopage',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
