# Generated by Django 5.1.6 on 2025-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_singleevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleevent',
            name='event_title',
            field=models.CharField(default='', max_length=140),
        ),
    ]
