# Generated by Django 5.1.6 on 2025-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_galleryindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopage',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='photopage',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
