# Generated by Django 5.1.6 on 2025-10-14 20:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_eventpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 9), ('event_list', 11)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional text to display with the image', 'label': 'Bildunterschrift', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts')], 'label': 'Position der Bildunterschrift'}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional URL to link the image to (external links only)', 'label': 'Optional Link', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption_position', 7), ('link', 8)]], {}), 10: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('Vortrag', 'Vortrag'), ('Hybride Vortrag', 'Hybride Vortrag'), ('Online Vortrag', 'Online Vortrag'), ('Beobachtungsabend', 'Beobachtungsabend'), ('Ausflug', 'Ausflug')], 'help_text': 'Liste von Veranstaltungen', 'label': 'Art der Veranstaltung', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('event_type', 10)]], {})}, default=[]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional text to display with the image', 'label': 'Bildunterschrift', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts')], 'label': 'Position der Bildunterschrift'}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional URL to link the image to (external links only)', 'label': 'Optional Link', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption_position', 7), ('link', 8)]], {})}, default=[]),
        ),
    ]
