# Generated by Django 5.2.7 on 2025-11-27 17:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_eventpage_body_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 12), ('event_list', 14)], block_lookup={0: ('home.models.common.HeadingBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('home.models.common.HeadingBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('home.models.common.HeadingBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional formatted text to display with the image', 'label': 'Bildunterschrift', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts')], 'label': 'Position der Bildunterschrift'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Kein Link'), ('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Link-Typ'}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Wählen Sie eine Seite aus dieser Website', 'label': 'Interne Seite', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Geben Sie eine vollständige URL ein (z.B. https://example.com)', 'label': 'Externe URL', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 9), ('external_url', 10)]], {'help_text': 'Optionaler Link für das Bild (interne Seite oder externe URL)', 'label': 'Optional Link'}), 12: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption_position', 7), ('link', 11)]], {}), 13: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('Vortrag', 'Vortrag'), ('Hybride Vortrag', 'Hybride Vortrag'), ('Online Vortrag', 'Online Vortrag'), ('Beobachtungsabend', 'Beobachtungsabend'), ('Ausflug', 'Ausflug')], 'help_text': 'Liste von Veranstaltungen', 'label': 'Art der Veranstaltung', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('event_type', 13)]], {})}, default=[]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 12)], block_lookup={0: ('home.models.common.HeadingBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('home.models.common.HeadingBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('home.models.common.HeadingBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'h5', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional formatted text to display with the image', 'label': 'Bildunterschrift', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts')], 'label': 'Position der Bildunterschrift'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Kein Link'), ('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Link-Typ'}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Wählen Sie eine Seite aus dieser Website', 'label': 'Interne Seite', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Geben Sie eine vollständige URL ein (z.B. https://example.com)', 'label': 'Externe URL', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 9), ('external_url', 10)]], {'help_text': 'Optionaler Link für das Bild (interne Seite oder externe URL)', 'label': 'Optional Link'}), 12: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption_position', 7), ('link', 11)]], {})}, default=[]),
        ),
    ]
