# Generated by Django 6.0.2 on 2026-03-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_eventpage_body_alter_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="show_in_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will appear in the sidebar with a link.",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="sidebar_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional icon image to display in the sidebar next to the link text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="sidebar_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to display in the sidebar. If empty, the page title will be used.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="show_in_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will appear in the sidebar with a link.",
            ),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="sidebar_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional icon image to display in the sidebar next to the link text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="sidebar_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to display in the sidebar. If empty, the page title will be used.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="show_in_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will appear in the sidebar with a link.",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="sidebar_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional icon image to display in the sidebar next to the link text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="sidebar_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to display in the sidebar. If empty, the page title will be used.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_in_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will appear in the sidebar with a link.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="sidebar_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional icon image to display in the sidebar next to the link text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="sidebar_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to display in the sidebar. If empty, the page title will be used.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="photopage",
            name="show_in_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will appear in the sidebar with a link.",
            ),
        ),
        migrations.AddField(
            model_name="photopage",
            name="sidebar_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional icon image to display in the sidebar next to the link text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="photopage",
            name="sidebar_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to display in the sidebar. If empty, the page title will be used.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="singleevent",
            name="show_in_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will appear in the sidebar with a link.",
            ),
        ),
        migrations.AddField(
            model_name="singleevent",
            name="sidebar_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional icon image to display in the sidebar next to the link text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="singleevent",
            name="sidebar_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to display in the sidebar. If empty, the page title will be used.",
                max_length=255,
            ),
        ),
    ]
