# Generated by Django 6.0.2 on 2026-03-17 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_add_sidebar_promotion'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopage',
            name='show_in_sidebar',
        ),
        migrations.RemoveField(
            model_name='photopage',
            name='sidebar_icon',
        ),
        migrations.RemoveField(
            model_name='photopage',
            name='sidebar_text',
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='show_in_sidebar',
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='sidebar_icon',
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='sidebar_text',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='show_in_sidebar',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird diese Seite mit einem Link im Seitenbalken angezeigt.'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='sidebar_icon',
            field=models.ForeignKey(blank=True, help_text='Optionales Symbolbild, das im Seitenbalken neben dem Link-Text angezeigt wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='sidebar_text',
            field=models.CharField(blank=True, default='', help_text='Text, der im Seitenbalken angezeigt werden soll. Wenn leer, wird der Seitentitel verwendet.', max_length=255),
        ),
        migrations.AlterField(
            model_name='galleryindexpage',
            name='show_in_sidebar',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird diese Seite mit einem Link im Seitenbalken angezeigt.'),
        ),
        migrations.AlterField(
            model_name='galleryindexpage',
            name='sidebar_icon',
            field=models.ForeignKey(blank=True, help_text='Optionales Symbolbild, das im Seitenbalken neben dem Link-Text angezeigt wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='galleryindexpage',
            name='sidebar_text',
            field=models.CharField(blank=True, default='', help_text='Text, der im Seitenbalken angezeigt werden soll. Wenn leer, wird der Seitentitel verwendet.', max_length=255),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='show_in_sidebar',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird diese Seite mit einem Link im Seitenbalken angezeigt.'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='sidebar_icon',
            field=models.ForeignKey(blank=True, help_text='Optionales Symbolbild, das im Seitenbalken neben dem Link-Text angezeigt wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='sidebar_text',
            field=models.CharField(blank=True, default='', help_text='Text, der im Seitenbalken angezeigt werden soll. Wenn leer, wird der Seitentitel verwendet.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_in_sidebar',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird diese Seite mit einem Link im Seitenbalken angezeigt.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar_icon',
            field=models.ForeignKey(blank=True, help_text='Optionales Symbolbild, das im Seitenbalken neben dem Link-Text angezeigt wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar_text',
            field=models.CharField(blank=True, default='', help_text='Text, der im Seitenbalken angezeigt werden soll. Wenn leer, wird der Seitentitel verwendet.', max_length=255),
        ),
    ]
