# Generated by Django 6.0.2 on 2026-04-19 13:33

import django.db.models.deletion
import home.models.common
import modelsearch.index
import taggit.managers
import wagtail.fields
import wagtail.images.models
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_photopage_show_in_sidebar_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('image', models.ImageField(blank=True, help_text='Bilder als statische Dateien oder animierte GIFs (PNG, JPG, GIF)', null=True, upload_to='images/%Y/%m/')),
                ('video', models.FileField(blank=True, help_text='Videodatei (MP4, WebM, Ogg)', null=True, upload_to='videos/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Statisches Bild'), ('gif', 'Animiertes GIF'), ('video', 'Videodatei')], default='image', help_text='Typ des Mediums', max_length=10)),
                ('media_alt_text', models.CharField(blank=True, default='', help_text='Beschreibung für Barrierefreiheit', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, default='', max_length=800)),
                ('author', models.CharField(blank=True, default='', max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(home.models.common.CommonContextMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 12), ('media_with_caption', 21), ('event_list', 23), ('multi_column', 28)], block_lookup={0: ('home.models.common.HeadingBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('home.models.common.HeadingBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('home.models.common.HeadingBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['anchor-identifier', 'h4', 'h5', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional formatted text to display with the image', 'label': 'Bildunterschrift', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts')], 'label': 'Position der Bildunterschrift'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Kein Link'), ('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Link-Typ'}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Wählen Sie eine Seite aus dieser Website', 'label': 'Interne Seite', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Geben Sie eine vollständige URL ein (z.B. https://example.com)', 'label': 'Externe URL', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 9), ('external_url', 10)]], {'help_text': 'Optionaler Link für das Bild (interne Seite oder externe URL)', 'label': 'Optional Link'}), 12: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption_position', 7), ('link', 11)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Bild'), ('gif', 'Animiertes GIF'), ('video', 'Video')], 'help_text': 'Wählen Sie den Typ des Mediums aus', 'label': 'Medientyp'}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Wählen Sie ein Bild oder eine GIF-Datei', 'label': 'Bild oder GIF', 'required': False}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Wählen Sie eine Videodatei (MP4, WebM, Ogg)', 'label': 'Videodatei', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Beschreibung für Barrierefreiheit (wird nicht angezeigt, aber von Screenreadern gelesen)', 'label': 'Alt-Text', 'max_length': 255, 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optionaler Text zur Beschreibung des Mediums', 'label': 'Bildunterschrift', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 9), ('external_url', 10)]], {'help_text': 'Optionaler Link für das Medien (interne Seite oder externe URL)', 'label': 'Optional Link'}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('true', 'Ja - Video und GIF starten automatisch'), ('false', 'Nein - Benutzer muss abspielen')], 'help_text': 'Nur für Videos und animierte GIFs', 'label': 'Autoplay'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('true', 'Ja - Wiederholen'), ('false', 'Nein - Einmal abspielen')], 'help_text': 'Nur für Videos und animierte GIFs', 'label': 'Schleife'}), 21: ('wagtail.blocks.StructBlock', [[('media_type', 13), ('image', 14), ('video', 15), ('media_alt_text', 16), ('caption', 17), ('caption_position', 7), ('link', 18), ('autoplay', 19), ('loop', 20)]], {}), 22: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('Vortrag', 'Vortrag'), ('Hybride Vortrag', 'Hybride Vortrag'), ('Online Vortrag', 'Online Vortrag'), ('Beobachtungsabend', 'Beobachtungsabend'), ('Ausflug', 'Ausflug')], 'help_text': 'Liste von Veranstaltungen', 'label': 'Art der Veranstaltung', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('event_type', 22)]], {}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1 Spalte'), ('2', '2 Spalten'), ('4', '4 Spalten')], 'help_text': 'Die Anzahl der Spalten für das Layout', 'label': 'Maximale Anzahl von Spalten'}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1 Spalte'), ('2', '2 Spalten'), ('4', '4 Spalten')], 'help_text': 'Die Mindestanzahl von Spalten auch auf mobilen Geräten', 'label': 'Minimale Anzahl von Spalten'}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Volle Breite'), ('half', '1/2 Breite (auf Desktop)'), ('quarter', '1/4 Breite (auf Desktop)')], 'help_text': 'Auf mobilen Geräten wird immer die volle Breite verwendet', 'label': 'Breite des Blocks'}), 27: ('wagtail.blocks.StreamBlock', [[('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 12), ('media_with_caption', 21), ('event_list', 23)]], {'label': 'Inhalt'}), 28: ('wagtail.blocks.StructBlock', [[('max_columns', 24), ('min_columns', 25), ('width', 26), ('content', 27)]], {})}, default=[]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 12), ('media_with_caption', 21), ('multi_column', 26)], block_lookup={0: ('home.models.common.HeadingBlock', (), {'form_classname': 'h1', 'label': 'Kopfzeile 1'}), 1: ('home.models.common.HeadingBlock', (), {'form_classname': 'h2', 'label': 'Kopfzeile 2'}), 2: ('home.models.common.HeadingBlock', (), {'form_classname': 'h3', 'label': 'Kopfzeile 3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['anchor-identifier', 'h4', 'h5', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional formatted text to display with the image', 'label': 'Bildunterschrift', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Oben'), ('bottom', 'Unten'), ('left', 'Links'), ('right', 'Rechts')], 'label': 'Position der Bildunterschrift'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Kein Link'), ('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Link-Typ'}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Wählen Sie eine Seite aus dieser Website', 'label': 'Interne Seite', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Geben Sie eine vollständige URL ein (z.B. https://example.com)', 'label': 'Externe URL', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 9), ('external_url', 10)]], {'help_text': 'Optionaler Link für das Bild (interne Seite oder externe URL)', 'label': 'Optional Link'}), 12: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption_position', 7), ('link', 11)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Bild'), ('gif', 'Animiertes GIF'), ('video', 'Video')], 'help_text': 'Wählen Sie den Typ des Mediums aus', 'label': 'Medientyp'}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Wählen Sie ein Bild oder eine GIF-Datei', 'label': 'Bild oder GIF', 'required': False}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Wählen Sie eine Videodatei (MP4, WebM, Ogg)', 'label': 'Videodatei', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Beschreibung für Barrierefreiheit (wird nicht angezeigt, aber von Screenreadern gelesen)', 'label': 'Alt-Text', 'max_length': 255, 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optionaler Text zur Beschreibung des Mediums', 'label': 'Bildunterschrift', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 9), ('external_url', 10)]], {'help_text': 'Optionaler Link für das Medien (interne Seite oder externe URL)', 'label': 'Optional Link'}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('true', 'Ja - Video und GIF starten automatisch'), ('false', 'Nein - Benutzer muss abspielen')], 'help_text': 'Nur für Videos und animierte GIFs', 'label': 'Autoplay'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('true', 'Ja - Wiederholen'), ('false', 'Nein - Einmal abspielen')], 'help_text': 'Nur für Videos und animierte GIFs', 'label': 'Schleife'}), 21: ('wagtail.blocks.StructBlock', [[('media_type', 13), ('image', 14), ('video', 15), ('media_alt_text', 16), ('caption', 17), ('caption_position', 7), ('link', 18), ('autoplay', 19), ('loop', 20)]], {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1 Spalte'), ('2', '2 Spalten'), ('4', '4 Spalten')], 'help_text': 'Die Anzahl der Spalten für das Layout', 'label': 'Maximale Anzahl von Spalten'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1 Spalte'), ('2', '2 Spalten'), ('4', '4 Spalten')], 'help_text': 'Die Mindestanzahl von Spalten auch auf mobilen Geräten', 'label': 'Minimale Anzahl von Spalten'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Volle Breite'), ('half', '1/2 Breite (auf Desktop)'), ('quarter', '1/4 Breite (auf Desktop)')], 'help_text': 'Auf mobilen Geräten wird immer die volle Breite verwendet', 'label': 'Breite des Blocks'}), 25: ('wagtail.blocks.StreamBlock', [[('h1', 0), ('h2', 1), ('h3', 2), ('paragraph', 3), ('image', 4), ('image_with_caption', 12), ('media_with_caption', 21)]], {'label': 'Inhalt'}), 26: ('wagtail.blocks.StructBlock', [[('max_columns', 22), ('min_columns', 23), ('width', 24), ('content', 25)]], {})}, default=[]),
        ),
        migrations.AlterField(
            model_name='photopage',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Wagtail-Bild', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
            bases=(wagtail.images.models.ImageFileMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CustomRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='home.customimage')),
            ],
            options={
                'unique_together': {('image', 'filter_spec', 'focal_point_key')},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
    ]
