# Generated by Django 6.0.2 on 2026-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_videopage_and_video_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="show_sidebar_on_mobile",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, wird der Seitenbalken auf mobilen Geräten oben auf der Seite angezeigt.",
            ),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="show_sidebar_on_mobile",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, wird der Seitenbalken auf mobilen Geräten oben auf der Seite angezeigt.",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="show_sidebar_on_mobile",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, wird der Seitenbalken auf mobilen Geräten oben auf der Seite angezeigt.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_sidebar_on_mobile",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, wird der Seitenbalken auf mobilen Geräten oben auf der Seite angezeigt.",
            ),
        ),
    ]
