# Generated by Django 6.0.2 on 2026-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_videopage_alter_eventpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='video',
        ),
        migrations.AddField(
            model_name='videopage',
            name='media_file',
            field=models.FileField(blank=True, help_text='Videodatei (MP4, WebM, Ogg) oder animiertes GIF', null=True, upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='media_type',
            field=models.CharField(choices=[('gif', 'Animiertes GIF'), ('video', 'Videodatei')], default='video', help_text='Typ des Mediums', max_length=10),
        ),
    ]
